module.exports =

   # → is Type
   is:              require('./is')
   isBoolean:       require('./isBoolean')
   isNumber:        require('./isNumber')
   isInt:           require('./isInt')
   isN:             require('./isN')
   isID:            require('./isID')
   isString:        require('./isString')
   isSymbol:        require('./isSymbol')
   isFunction:      require('./isFunction')
   isAsyncFunction: require('./isAsyncFunction')
   isArray:         require('./isArray')
   isArrayLike:     require('./isArrayLike')
   isBuffer:        require('./isBuffer')
   isRegExp:        require('./isRegExp')
   isDate:          require('./isDate')
   isError:         require('./isError')
   isPromise:       require('./isPromise')
   isObject:        require('./isObject')
   isPlainObject:   require('./isPlainObject')
   isNil:           require('./isNil')
   isNaN:           require('./isNaN')
   isAny:           require('./isAny')

   # → is String-Format
   isSpace: require('./isSpace')
   isEmail: require('./isEmail')
   isURL:   require('./isURL')