suite '~is', ->

   require('./is')
   require('./isBoolean')
   require('./isNumber')
   require('./isInt')
   require('./isN')
   require('./isID')
   require('./isString')
   require('./isSymbol')
   require('./isFunction')
   require('./isAsyncFunction')
   require('./isArray')
   require('./isArrayLike')
   require('./isBuffer')
   require('./isRegExp')
   require('./isDate')
   require('./isError')
   require('./isPromise')
   require('./isObject')
   require('./isPlainObject')
   require('./isNil')
   require('./isNaN')