suite '~is', ->

   # → is Type
   require('./is')
   require('./isBoolean')
   require('./isNumber')
   require('./isInt')
   require('./isN')
   require('./isID')
   require('./isString')
   require('./isSymbol')
   require('./isFunction')
   require('./isAsyncFunction')
   require('./isArray')
   require('./isArrayLike')
   require('./isBuffer')
   require('./isRegExp')
   require('./isDate')
   require('./isError')
   require('./isPromise')
   require('./isObject')
   require('./isPlainObject')
   require('./isNil')
   require('./isNaN')
   require('./isEmpty')
   require('./isMin')
   require('./isMax')

   # → is String-Format
   require('./isEmail')
   require('./isURL')
   require('./isBooleanString')
   require('./isNumberString')
   require('./isSpace')