module.exports =

   INVALID_PARAMS:        'INVALID_PARAMS'
   INVALID_DATA:          'INVALID_DATA'
   FILE_NOT_FOUND:        'FILE_NOT_FOUND'
   DIR_NOT_FOUND:         'DIR_NOT_FOUND'
   TEXT_PARSE_FAIL:       'TEXT_PARSE_FAIL'
   MONGO_DB_CONNECT_FAIL: 'MONGO_DB_CONNECT_FAIL'