module.exports = Object.assign({},
   require('./core')
   require('./is')
   require('./test')
   require('./date')
   require('./file')
   require('./http')
   require('./code')
   require('./mongo')
)