suite '~test', ->

   require('./Tester@name')
   require('./Tester@required')
   require('./Tester@in')
   require('./Tester@is')
   require('./Tester@boolean')
   require('./Tester@number')
   require('./Tester@int')
   require('./Tester@natural')
   require('./Tester@id')
   require('./Tester@string')
   require('./Tester@buffer')
   require('./Tester@date')
   require('./Tester@array')
   require('./Tester@plainObject')
   require('./Tester@min')
   require('./Tester@max')
   require('./Tester@check')